# Generated by Django 4.1.4 on 2023-01-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('guest_from', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/uploads', verbose_name='background image')),
                ('name', models.CharField(max_length=255, verbose_name='programme')),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(blank=True, default='Victorious Living Church International, Kasoa', max_length=255, null=True)),
                ('guests', models.ManyToManyField(blank=True, null=True, to='programmes.guest')),
            ],
        ),
    ]
