# Generated by Django 4.1.4 on 2023-01-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_guest_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='datetime',
            field=models.DateTimeField(verbose_name='date & time'),
        ),
    ]
