# Generated by Django 4.2 on 2023-04-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0014_alter_guest_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='guests',
            field=models.ManyToManyField(to='programmes.guest'),
        ),
    ]
