# Generated by Django 4.2 on 2023-04-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0016_alter_programme_guests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['name']},
        ),
    ]
