# Generated by Django 4.2 on 2023-04-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0017_alter_programme_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['name']},
        ),
    ]
