# Generated by Django 4.2 on 2023-04-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0018_alter_guest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='image',
            field=models.ImageField(blank=True, default='static/images/programme_default.jpg', null=True, upload_to='images', verbose_name='background image'),
        ),
    ]
