# Generated by Django 4.2 on 2023-04-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0022_alter_guest_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='picture',
            field=models.ImageField(default='images/no_image.png', upload_to='images'),
        ),
    ]
