# Generated by Django 4.2 on 2023-04-24 14:20

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0024_alter_guest_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='picture',
            field=django_fields.fields.DefaultStaticImageField(default='images/no_image.png', upload_to='images'),
        ),
    ]
