# Generated by Django 4.2 on 2023-04-24 14:23

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0026_alter_guest_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='picture',
            field=django_fields.fields.DefaultStaticImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
