# Generated by Django 4.2 on 2023-04-27 18:38

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0027_alter_guest_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='image',
            field=django_fields.fields.DefaultStaticImageField(blank=True, null=True, upload_to='images', verbose_name='background image'),
        ),
    ]
