# Generated by Django 4.2 on 2023-04-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0028_alter_programme_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeBackgroundImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Programme Background Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='programme',
            name='image',
        ),
        migrations.AddField(
            model_name='programme',
            name='image',
            field=models.ManyToManyField(default='images/programme_default.jpg', to='programmes.programmebackgroundimgs'),
        ),
    ]
