# Generated by Django 4.2 on 2023-04-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0029_programmebackgroundimgs_remove_programme_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='image',
            field=models.ManyToManyField(blank=True, default='images/programme_default.jpg', null=True, to='programmes.programmebackgroundimgs', verbose_name='Background image'),
        ),
    ]
