# Generated by Django 4.2 on 2023-04-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0031_alter_programme_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmebackgroundimgs',
            options={'verbose_name_plural': 'Programme Background Images'},
        ),
    ]
