# Generated by Django 4.2 on 2023-04-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0032_alter_programmebackgroundimgs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='image',
            field=models.ManyToManyField(blank=True, to='programmes.programmebackgroundimgs', verbose_name='Background image'),
        ),
    ]
