# Generated by Django 4.2 on 2023-04-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gelleries'},
        ),
    ]
