# Generated by Django 4.1.4 on 2023-01-01 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Question by'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='winner',
            field=models.ManyToManyField(blank=True, null=True, to='chat.winner', verbose_name='select winner(s)'),
        ),
    ]
