# Generated by Django 4.1.4 on 2023-01-01 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fellowships', '0001_initial'),
        ('programmes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(default='Victorious Living Church International, Kasoa', max_length=255)),
                ('image', models.ImageField(blank=True, default='static/images/sunday_service_bg.jpg', null=True, upload_to='static/uploads', verbose_name='background image')),
                ('guests', models.ManyToManyField(blank=True, null=True, to='programmes.guest', verbose_name='Invited Guests')),
                ('music_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fellowships.musicgroup')),
                ('preacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preacher', to=settings.AUTH_USER_MODEL, verbose_name='preacher')),
                ('preacher2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preacher', to='programmes.guest', verbose_name='preacher (guest)')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
                ('teacher2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='programmes.guest', verbose_name='teacher (guest)')),
            ],
        ),
    ]
