# Generated by Django 4.1.4 on 2023-01-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sundayservice',
            name='date',
        ),
        migrations.AddField(
            model_name='sundayservice',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date & time'),
        ),
    ]
