# Generated by Django 4.1.4 on 2023-01-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_sundayservice_date_sundayservice_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sundayservice',
            old_name='datetime',
            new_name='date',
        ),
    ]
