# Generated by Django 4.1.4 on 2023-01-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_datetime_sundayservice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sundayservice',
            old_name='date',
            new_name='datetime',
        ),
    ]
