# Generated by Django 4.1.5 on 2023-02-11 22:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_date_sundayservice_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
