# Generated by Django 4.2 on 2023-04-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0015_alter_programme_guests'),
        ('service', '0005_sundayrecap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundayservice',
            name='guests',
            field=models.ManyToManyField(to='programmes.guest', verbose_name='Invited Guests'),
        ),
    ]
