# Generated by Django 4.2 on 2023-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0016_alter_programme_guests'),
        ('service', '0006_alter_sundayservice_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundayservice',
            name='guests',
            field=models.ManyToManyField(blank=True, to='programmes.guest', verbose_name='Invited Guests'),
        ),
    ]
