# Generated by Django 4.2 on 2023-04-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_sundayservice_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundayservice',
            name='image',
            field=models.ImageField(blank=True, default='static/images/sunday_service_bg.jpg', null=True, upload_to='images', verbose_name='background image'),
        ),
    ]
