# Generated by Django 4.2 on 2023-04-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_sundayservice_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sundayservice',
            options={'verbose_name_plural': 'Sunday service'},
        ),
    ]
