# Generated by Django 4.2 on 2023-04-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowship',
            name='meeting_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musicgroup',
            name='name',
            field=models.CharField(max_length=50, verbose_name='music group'),
        ),
    ]
