# Generated by Django 4.2 on 2023-04-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowships', '0004_meetingdays_remove_fellowship_meeting_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowship',
            name='meeting_days',
            field=models.ManyToManyField(blank=True, to='fellowships.meetingdays'),
        ),
    ]
