# Generated by Django 4.2 on 2023-04-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fellowships', '0005_alter_fellowship_meeting_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingDays',
            new_name='MeetingDay',
        ),
    ]
