# Generated by Django 4.1.4 on 2023-01-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='datetime',
            field=models.DateField(auto_now_add=True, verbose_name='date & time'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='date & time'),
        ),
    ]
