# Generated by Django 4.2 on 2023-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_quiz_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='winner',
            field=models.ManyToManyField(blank=True, to='chats.winner', verbose_name='select winner(s)'),
        ),
    ]
