# Generated by Django 4.2 on 2023-04-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_quiz_winner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['chat']},
        ),
    ]
