# Generated by Django 4.2 on 2023-04-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_carouselimg_image_alter_comment_chat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimg',
            options={'verbose_name_plural': 'Carousel Images'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
