# Generated by Django 4.2 on 2023-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_alter_carouselimg_options_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='editted',
            field=models.BooleanField(default=False),
        ),
    ]
