# Generated by Django 4.2 on 2023-04-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_comment_editted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-datetime']},
        ),
    ]
