# Generated by Django 4.2 on 2023-04-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
