# Generated by Django 4.2 on 2023-04-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0002_alter_leader_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['member']},
        ),
    ]
