# Generated by Django 4.2 on 2023-04-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0003_alter_leader_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadertitle',
            options={'ordering': ['name']},
        ),
    ]
