# Generated by Django 4.1.4 on 2023-01-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, default='static/uploads/no_image.jpeg', null=True, upload_to='static/uploads'),
        ),
    ]
