# Generated by Django 4.1.4 on 2023-01-02 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
