# Generated by Django 4.2 on 2023-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_member_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, default='/static/images/no-image.png', null=True, upload_to='images'),
        ),
    ]
