# Generated by Django 4.2 on 2023-04-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowships', '0002_alter_fellowship_meeting_days_alter_musicgroup_name'),
        ('members', '0015_alter_member_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fellowship',
            field=models.ManyToManyField(to='fellowships.fellowship', verbose_name='fellowship group'),
        ),
    ]
