# Generated by Django 4.2 on 2023-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowships', '0002_alter_fellowship_meeting_days_alter_musicgroup_name'),
        ('members', '0016_alter_member_fellowship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterField(
            model_name='member',
            name='fellowship',
            field=models.ManyToManyField(blank=True, to='fellowships.fellowship', verbose_name='fellowship group'),
        ),
    ]
