# Generated by Django 4.2 on 2023-04-24 14:10

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_alter_member_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=django_fields.fields.DefaultStaticImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
